version: '2'
services:

 ##########################################################
  rabbitmq:
    container_name: RabbitMQ
    image: rabbitmq:3-management-alpine
    volumes:
      - mq_data:/var/lib/rabbitmq/mnesia
    ports:
      - "15672:15672"
      - "5672:5672"    
    networks:
      - log
    environment:
      RABBITMQ_DEFAULT_USER: logUser
      RABBITMQ_DEFAULT_PASS: logPwd
      RABBITMQ_DEFAULT_VHOST: EnterpriseLog
  ##########################################################
  logstash:
    container_name: LogStash    
    image: docker.elastic.co/logstash/logstash:5.6.4
    volumes:
      - ./product.logstash.conf:/config/product.logstash.conf    
    depends_on:
      - rabbitmq
      - elasticsearch
    links:
      - rabbitmq:AMQPServer
      - elasticsearch:elasticsearch
    networks:
      - log    
    command: ["-f", "/config/product.logstash.conf"]
  ##########################################################
  elasticsearch:
    container_name: ElasticSearch    
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.4
    environment: 
      - "http.host:0.0.0.0"
      - "transport.host:127.0.0.1"
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes: 
      - ./product.elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - log
  ##########################################################
  kibana:
    container_name: Kibana    
    image: docker.elastic.co/kibana/kibana:5.6.4
    volumes:
      - ./product.kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:elasticsearch
    ports:
      - "5601:5601"
    networks:
      - log

volumes:
  mq_data:

networks:
  log:
    driver: bridge